server.port=8080
server.servlet.context-path=/api/camel/v1
camel.main.name = CamelKafkaExample
# Camel Rest Config
camel.rest.binding-mode = json
camel.rest.api-property.api.default.response=false

# Camel Kafka Config
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.security-protocol=SASL_PLAINTEXT
camel.component.kafka.sasl-jaas-config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
camel.component.kafka.sasl-mechanism=PLAIN
camel.component.kafka.auto-offset-reset=latest
camel.component.kafka.consumers-count=5
camel.component.kafka.group-id=camel-kafka-example

# expose actuator endpoint via HTTP
management.endpoints.web.exposure.include=info,health,camelroutes

# turn on actuator health check
management.endpoint.health.enabled = true

# allow to obtain basic information about camel routes (read only mode)
management.endpoint.camelroutes.enabled = true
management.endpoint.camelroutes.read-only = true

#logging.level.org.apache.camel=DEBUG
#logging.level.org.apache.kafka.clients.consumer=DEBUG
#logging.level.org.apache.camel.component.kafka=DEBUG